DOMAIN,www.baidu.com
DOMAIN-SUFFIX,cn
DOMAIN-SUFFIX,facetime.apple.com
DOMAIN-SUFFIX,ess.apple.com
DOMAIN-SUFFIX,push.apple.com
DOMAIN-SUFFIX,identity.apple.com
DOMAIN-SUFFIX,init.itunes.apple.com
DOMAIN-SUFFIX,qq.com
DOMAIN-SUFFIX,qqmusic.qq.com
DOMAIN-SUFFIX,music.qq.com
DOMAIN-SUFFIX,music.tc.qq.com
DOMAIN-SUFFIX,gtimg.com
DOMAIN-SUFFIX,wegame.com
DOMAIN-SUFFIX,riotgames.com
DOMAIN-SUFFIX,some.url
DOMAIN-SUFFIX,lolesports.com
DOMAIN-SUFFIX,api.lolesports.com
DOMAIN-SUFFIX,cm.steampowered.com
DOMAIN-SUFFIX,test.steampowered.com
DOMAIN-SUFFIX,shared.fastly.steamstatic.com
DOMAIN-SUFFIX,dianping.com
DOMAIN-SUFFIX,maoyan.com
DOMAIN-SUFFIX,meituan.com
DOMAIN-SUFFIX,meituan.net
DOMAIN-SUFFIX,mtyun.com
DOMAIN-SUFFIX,neixin.cn
DOMAIN-SUFFIX,sankuai.com
DOMAIN-SUFFIX,sxjkjyx.com
DOMAIN-SUFFIX,jtjt.info
DOMAIN-SUFFIX,fanovel.com
DOMAIN-KEYWORD,tencent
DOMAIN-KEYWORD,weixin
DOMAIN-KEYWORD,wechat
DOMAIN-KEYWORD,meituan
DOMAIN-KEYWORD,steamserver.net
DOMAIN-KEYWORD,sxjk
DOMAIN-KEYWORD,sxjt
DOMAIN-KEYWORD,jtjt
DOMAIN-KEYWORD,sxjtjt
DOMAIN-KEYWORD,fanovel
