import json
import sys
import os

def convert(src_path, dest_path):
    if not os.path.exists(src_path):
        print(f"Error: Source {src_path} not found")
        sys.exit(1)

    os.makedirs(os.path.dirname(dest_path), exist_ok=True)

    try:
        with open(src_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        # 兼容嵌套和扁平结构
        rules_data = data.get("rules", [data])[0]
        
        # Rule-set 头部注释
        output = [
            f"# Surge Rule-Set: {os.path.basename(dest_path)}",
            f"# Generated by Exslr\n"
        ]

        # 映射关系 (仅保留类型和内容)
        mapping = {
            "domain": "DOMAIN",
            "domain_suffix": "DOMAIN-SUFFIX",
            "domain_keyword": "DOMAIN-KEYWORD",
            "ip_cidr": "IP-CIDR"
        }

        # 1. 处理标准分流规则
        for sb_key, surge_type in mapping.items():
            for item in rules_data.get(sb_key, []):
                # 只输出 "类型,内容"
                output.append(f"{surge_type},{item}")

        # 2. 处理不支持的字段 (Regex & Process) 仅作注释提醒
        unsupported_mapping = {
            "domain_regex": "REGEX",
            "process_name": "PROCESS-NAME",
            "process_path": "PROCESS-PATH"
        }

        has_unsupported = False
        for sb_key, label in unsupported_mapping.items():
            items = rules_data.get(sb_key, [])
            if items:
                if not has_unsupported:
                    output.append(f"\n# --- Unsupported in Surge Rule-Set ---")
                    has_unsupported = True
                for item in items:
                    output.append(f"# {label}: {item}")

        with open(dest_path, 'w', encoding='utf-8') as f:
            f.write("\n".join(output))
        
        print(f"Success: {src_path} -> {dest_path}")

    except Exception as e:
        print(f"Failed to convert {src_path}: {e}")
        sys.exit(1)

if __name__ == "__main__":
    if len(sys.argv) == 3:
        convert(sys.argv[1], sys.argv[2])
    else:
        print("Usage: python3 convert_to_surge.py <input_json> <output_conf>")
