name: Update Rules in Branch Surge Every Week

on:
  schedule:
    - cron: '0 0 * * 0'
    
  workflow_dispatch:
  
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'
  
jobs:
  update-surge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run convert script
        run: python scripts/convert_json_to_conf.py

      - name: Commit and Push to Surge Branch
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add surge/
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Auto Update Rules $(date +'%Y-%m-%d')"
            git push
          fi
